name: 'Hello World'
description: 'changes on master.xml file'
branding:
  icon: 'package'
  color: 'black'
inputs:
  repo-token:
    description: 'Github token secret'
    required: true
  content:
    description: 'Content from file'
    required: true
    default: 'F en el chat'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'