name: FILES CHANGE

on:
  push:
    branches:
    - main

jobs:
  scan_files:
    runs-on: ubuntu-latest
    name: verify files changed
    outputs:
      file_added: ${{ steps.file_changes.outputs.files_added }}
      file_modified: ${{ steps.file_changes.outputs.files_modified }}
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          fileOutput: 'sql'
      - name: print Files modified or added
        run: |
          echo 'Archivos modificados: ${{ steps.file_changes.outputs.files_modified }}'
          echo 'Archivos agregados: ${{ steps.file_changes.outputs.files_added }}'
  
  Save_changes_Files:
    runs-on: ubuntu-latest
    needs: scan_files
    steps:
      - name: verify result
        run: |
           echo 'Archivos modificados: ${{ needs.scan_files.outputs.file_modified }}'
           echo 'Archivos agregados: ${{ needs.scan_files.outputs.file_added }}'
  