on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Job to print repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: token repo
        id: token
        uses: ./
        with:
          repo-token: ${{ secrets.REPOSITORY_TOKEN }}"
      - name: Get the output time
        run: echo "The time was ${{ steps.token.outputs.time }}"