name: Change file .xml action

on:
  push:
    branches:
    - main

jobs:
  scan_files:
    runs-on: ubuntu-latest
    name: verify files changed
    outputs:
      file_added: ${{ steps.file_changes.outputs.files_added }}
      file_modified: ${{ steps.file_changes.outputs.files_modified }}
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          fileOutput: 'sql'
      - name: print Files modified or added
        run: |
          echo 'Archivos modificados: ${{ steps.file_changes.outputs.files_modified }}'
          echo 'Archivos agregados: ${{ steps.file_changes.outputs.files_added }}'
  
  change-file:
    runs-on: ubuntu-latest
    needs: scan_files
    steps:
      # - name: verify result
      #   run: |
      #      echo "Archivos modificados: $FILE_MODIFIED"
      #      echo "Archivos agregados: $FILE_ADDED"
      #   env:
      #     FILE_ADDED: ${{ needs.scan_files.outputs.file_added }}
      #     FILE_MODIFIED: ${{ needs.scan_files.outputs.file_modified }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: token repo
        id: token
        uses: ./
        with:
          repo-token: ${{ secrets.REPOSITORY_TOKEN }}
          files-added: ${{ needs.scan_files.outputs.file_added }}
      - name: Get the output time
        run: echo "The time was ${{ steps.token.outputs.time }}"



  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: Job to print repository
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: token repo
  #       id: token
  #       uses: ./
  #       with:
  #         repo-token: ${{ secrets.REPOSITORY_TOKEN }}
  #         content: 'F'
  #     - name: Get the output time
  #       run: echo "The time was ${{ steps.token.outputs.time }}"